basePath: /
definitions:
  models.DataReq:
    properties:
      customer_name:
        type: string
      items:
        items:
          $ref: '#/definitions/models.ItemReq'
        type: array
    type: object
  models.DataRes:
    properties:
      customer_name:
        type: string
      items:
        items:
          $ref: '#/definitions/models.Item'
        type: array
      order_id:
        type: integer
      ordered_at:
        type: string
    type: object
  models.Item:
    properties:
      description:
        type: string
      item_code:
        type: string
      item_id:
        type: integer
      order_id:
        type: integer
      quantity:
        type: integer
    type: object
  models.ItemReq:
    properties:
      description:
        type: string
      item_code:
        type: string
      item_id:
        type: integer
      quantity:
        type: integer
    type: object
  views.GetAllPeopleSwagger:
    properties:
      error: {}
      message:
        example: GET_SUCCESS
        type: string
      payload:
        items:
          $ref: '#/definitions/models.DataRes'
        type: array
      status:
        example: 200
        type: integer
    type: object
host: localhost:4000
info:
  contact:
    email: teguh.afdilla138@gmail.com
    name: Teguh Ridho Afdilla
  description: Assignment 2 Kelas A
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: v1.0
paths:
  /v1/order:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.GetAllPeopleSwagger'
      summary: Get all order
      tags:
      - order
    post:
      consumes:
      - application/json
      parameters:
      - description: Add New Order
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.DataReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.GetAllPeopleSwagger'
      summary: Add new order
      tags:
      - order
    put:
      consumes:
      - application/json
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update New Order
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.DataReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.GetAllPeopleSwagger'
      summary: Update data order
      tags:
      - order
  /v1/order/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.GetAllPeopleSwagger'
      summary: Delete data order
      tags:
      - order
swagger: "2.0"
